language: python
python:
- '3.7'
addons:
  apt:
    packages:
    - lmodern
    - texlive-fonts-recommended
    - texlive-generic-recommended
    - texlive-fonts-extra
    - texlive-latex-extra
    - texlive-science
    - texlive-math-extra
    - texlive-lang-french
script:
- pip install pygrep pygit2 pdfrw
- git clone https://github.com/LaurentClaessens/pytex
- sed -i 's/\/usr\/bin\/python3/\/usr\/bin\/env python3/' pytex/pytex
- PATH=$PATH:$PWD/pytex pytex lst_frido.py | grep "^[(\!]"
- PATH=$PATH:$PWD/pytex pytex lst_giulietta.py | grep "^[(\!]"
deploy:
  provider: releases
  api_key:
    secure: FyxYsrWC4vEDeP5OjHbHjAhylhuw1CyvGkLIJa17OyvYF2YdNof4Hnr1Xcpj6rQRt6SYeWezntQGE7BcDAQ/RD08KAiyFFqzOTU66HYlydHBNdl8pAGxYS5345v8g43I38YZIh32Ajal2KPgdOR+0fNxAyXuqYIs6CAH3X1DnfXJERhrQlFZ6EaBRbF//t14S/9ma/dg9/L3ECW8p9oKz8A/IHLrZJFIwARwm3AgyV5TCM3tcKhzXmB1ynMXsnal3BsoxHJ4mqxSb3oSdNfy4meqr5sVeEAFsP3a/B4jh/sBCfYjQNNGqU1l2rj76433WIJQvx1/yvDkwr8l3jfHqk4qY3gxedD49SIy2zUVYbmXGq6IGFnLnynkXA80Ww5wGPKipalBcXO9A6gZ6RtKwiilML8ep5Hrlug+lHBMPpvdEA2xwOZdMrlq1BCXCeAUOoQBxPPEzpu7BFv4PFqG6IZWC6CjdQp4LOQV1ufZrWlkmOKGt8Gyxg5UdqY7vCakDrmgnL1wMB/c01pCEHCOWoA44BsCDdlHN8ZUk5l8WPDkuEZ0mSpUCCLQ4R2Szx9iAKvcY6FXYw1kBMduJoaRofR2j7LexpDaoDkUeh4Fkw56ooEMVMrdlEJjDX2AZCxX8w0mFHjOn5rNeSucOJorCMQUANyRH+eUaLZFsMZrU2Y=
  file:
  - frido.pdf
  - giulietta.pdf
  skip_cleanup: true
  on:
    all_branches: true
