language: python
python:
 - "3.7"
addons:
  apt:
    packages:
     - lmodern
     - texlive-fonts-recommended
     - texlive-generic-recommended
     - texlive-fonts-extra
     - texlive-latex-extra
     - texlive-science
     - texlive-math-extra
     - texlive-lang-french

script:
 - pip install pygrep pygit2 pdfrw
 - git clone https://github.com/LaurentClaessens/pytex
 - sed -i 's/\/usr\/bin\/python3/\/usr\/bin\/env python3/' pytex/pytex
 - PATH=$PATH:$PWD/pytex pytex lst_frido.py
 - PATH=$PATH:$PWD/pytex pytex lst_frido.py --verif
 - PATH=$PATH:$PWD/pytex pytex lst_giulietta.py
 - PATH=$PATH:$PWD/pytex pytex lst_giulietta.py --verif

deploy:
 provider: releases
 file:
 - frido.pdf
 - giuletta.pdf
 skip_cleanup: true
 on:
   tags: true
