language: python
python:
- '3.7'

# Skip build for tag added by deployment of latest release.
branches:
 except:
 - latest

addons:
  apt:
    packages:
    - lmodern
    - texlive-fonts-recommended
    - texlive-generic-recommended
    - texlive-fonts-extra
    - texlive-latex-extra
    - texlive-science
    - texlive-math-extra
    - texlive-lang-french

script:
- pip install pygrep pygit2 pdfrw
- git clone https://github.com/LaurentClaessens/pytex
- sed -i 's/\/usr\/bin\/python3/\/usr\/bin\/env python3/' pytex/pytex
- PATH=$PATH:$PWD/pytex pytex lst_frido.py | grep "^[(\!]"
#- PATH=$PATH:$PWD/pytex pytex lst_frido.py
- mv 0-lefrido.pdf frido.pdf
- PATH=$PATH:$PWD/pytex pytex lst_giulietta.py | grep "^[(\!]"
#- PATH=$PATH:$PWD/pytex pytex lst_giulietta.py
- mv 0-giulietta.pdf giulietta.pdf

# Tag 'latest' before deploying
before_deploy:
- export TRAVIS_TAG=latest
- git tag -f $TRAVIS_TAG
deploy:
  provider: releases
  name: latest
  body: "Les dernières versions du Frido et de Giulietta."
  # To fill the "secure" field:
  # In github, click on profile picture, Settings, Developer settings, Personal access tokens, Generate new token, toggle repo_deployment
  # sudo apt-get install ruby-all-dev
  # sudo gem install travis -v 1.8.10 --no-rdoc --no-ri
  # travis encrypt <api key>
  api_key:
    secure: e3vB7v6qi06VaWZgrKW1h0qhvbrKUC0wNNCgG+GZE6/TawRrwhAaMqUmHNgrRcJ17H2eyHlfuAEoudJ6AaIZJbnthAlKGdICIJWuamE8wIlVffSIpTI/F/c6rwnhxwYhLgLMkdZ5jp5xeTnUV3A/xrMdBgkgCwfPxmiotkCMGnjV75iJ4qLdrN+3/n2n58WQAn5Fei/ZMEH4S9ESUqYb1QO4IDLZDQfjjUyUsPXb2ZvslfbHQTRKuJXNK4kqBJNWqs4YwNqCZasRJf4T9G8DIHTuoEoUE9veAF1USPJSJ/y+k9x9OXWn1tpk1SbLm+DLskdNyJItPVASHhuNU5CQo6zteVDJ2OajaD2GifdKS9n4VCY1Nrgk3OEKy6cHDBCtq8+YfUJUDfViw+u26kpJDq56Xk31fd0LdBvAIo2Fo7K0c16D5eoFtSNhvTIGSOtpx/B+5JLJDH2QQC07FHogbC+9hARGwFTW4q+/Sh8s0Fa0b5GCCKJCIc5PVewNoLhL4f7jaJF5fXQY7MVeDURNDHnaT0Dfh/W/m8wtGiYlBeERlI4iL+sStFAGzCZGLZilRnm81zPuOG7boHhVRMcDeBq2NYOeFukQOytVSEV0ScJlPo+fXKDHoqvqzLICI6plTm/9xkOnddMBb8BU9MQC83hJuc9yknBVdZ2bUdyMl9Y=
  file:
  - frido.pdf
  - giulietta.pdf
  skip_cleanup: true
  overwrite: true
  on:
    tags: false
    branch:
    - master
    - travis
